name: echo
description: A new Flutter project.
publish_to: "none"
version: 1.1.0+3

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  flutter_secure_storage: ^8.0.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  jwt_decoder: ^2.0.1
  provider: ^6.0.5
  ionicons: ^0.2.2
  video_player: ^2.9.2
  chewie: ^1.8.5
  socket_io_client: ^3.0.0
  go_router: ^14.3.0
  collection: ^1.18.0
  file_picker: ^10.1.2
  mime: ^2.0.0
  http_parser: ^4.1.2
  appmetrica_plugin: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  assets:
    - assets/images/
  uses-material-design: true

flutter_launcher_icons:
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  android:
    adaptive_icon_background: "#FFFFFF"
    adaptive_icon_foreground: "assets/images/app_icon.png"
  web:
    generate: true
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
