name: build web
run-name: build web
on:
  push:
    branches: ['master', 'feature/flutter-web-ci']
    paths:
      - 'echo/**'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build docker image
        working-directory: echo
        run: docker build -t echo-web .
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image to GitHub Container Registry
        run: | 
          IMAGE_PATH=$(echo 'print("${{ github.repository }}".lower())' | python3 -)
          docker tag echo-web ghcr.io/$IMAGE_PATH/echo-web:latest 
          docker push ghcr.io/$IMAGE_PATH/echo-web:latest