name: build web
run-name: build web
on:
  push:
    branches:
      - master
      - feature/flutter-web-ci
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build docker image
        working-directory: echo
        run: docker build -t echo-web .
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image to GitHub Container Registry
        run: | 
          OWNER=$(echo 'print("${{ github.repository_owner }}".lower())' | python3 -)
          docker tag echo-web ghcr.io/$OWNER/echo-web:latest 
          docker push ghcr.io/$OWNER/echo-web:latest